### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by derek-adair** [no-dice/django-bootstrap-themes#10]
1. Is there any reason you stopped developing?
2. This seems complete, is it ready to use in the wild?
3. Is there anything else you would like to see done to this project?
4. Are you even still using this?

**Comment by tsbarnes** [comment]
1. Most of my recent projects have not been web-based, so it hasn't been a priority.  I am still maintaining it however, so I'll fix problems people run into with it.
2. It is complete and ready to use, yes.
3. I'd love for it to be easier for people to add their own themes.
4. Not currently, no.

**Comment by derek-adair** [comment]
Thank you for your time in developing this, and your response.

in regards to 3; do you mean to make it easier for the end user, the developer, or both?

**Comment by tsbarnes** [comment]
@derek-adair : for developers.

**Comment by derek-adair** [comment]
I see, its not exactly clear on how to even do that....

**Comment by derek-adair** [comment]
Do i just add my theme to ./bootstrap_themes/static/bootstrap/THEME_NAME and then run build_css.sh?

**Comment by tsbarnes** [comment]
You would also need to edit ./bootstrap_themes/__init__.py if you want it to show up in the list of themes (for example, if you're making the theme user-selectable).
