### ISSUE TITLE
Interaction with bootstrap3 ?

### ISSUE THREAD

**Issue by shearichard** [no-dice/django-bootstrap-themes#6]
Thanks for making django-bootstrap-themes available - looks very useful.

I'm trying to use it on a little demo project I'm doing but I don't get any themeing.

I'm wondering how django-bootstrap-themes coexists with django-bootstrap3 ?

I assumed that you could layer dbt on top of db3 but as I'm not getting any results I'm thinking again !

My template looks like this

```
{% extends 'chnnlsdmo/bootstrap.html' %}

{% load bootstrap3 %}
{% load bootstrap_themes %}
{% bootstrap_script use_min=True %}
{% bootstrap_styles theme='superhero' type='css' %}

{% block bootstrap3_content %}
    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>

        <p>
            <a href="{% url 'index' %}">index</a>
        </p>

        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}
```
If you've got any knowledge on this I'd be grateful to hear your views.

**Comment by shearichard** [comment]
Sorry I should included the real template ... the one above is the base template. 

```
{% extends 'chnnlsdmo/base.html' %}
{% load bootstrap3 %}

{% block title %}Channels Demo ... or ... flipping flags{% endblock %}

{% block content %}
    This is <em>bootstrap3</em> for <strong>Django</strong>.
{% endblock %}
```

**Comment by tsbarnes** [comment]
Because of the way bootstrap themes work, Bootstrap is fully included, you don't need django-bootstrap3.  By adding django-bootstrap3, it's actually overriding the theme's Bootstrap styles with the default ones.

**Comment by shearichard** [comment]
Thanks very much for your advice, after removing the django-bootstrap3 stuff it's now working.
